import React from "react";
import Head from "next/head";
import { useAppContext } from "contexts/AppContext";
import { motion } from "framer-motion";
import { GlobalStyles, darkTheme, lightTheme } from "styles/global.styles";
import Navbar from "components/Navbar";
import Footer from "components/Footer";
import { ThemeProvider } from "styled-components";
import { AnimatePresence } from "framer-motion";
import SearchBar from "./SearchBar";

const Layout = ({ children }) => {
  const { theme, isSearchBarOpen } = useAppContext();

  return (
    <motion.main
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <Head>
        <title>GigaTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme === "light" ? lightTheme : darkTheme}>
        <GlobalStyles />
        <Navbar />
        <AnimatePresence mode="popLayout">
          {isSearchBarOpen && <SearchBar />}
        </AnimatePresence>
        {children}
        <Footer />
      </ThemeProvider>
    </motion.main>
  );
};

export default Layout;
